agencies/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # home url
    path('', include('apps.home.urls')),
    # account url
    path('logout/', include('apps.account.logout.urls')),
    path('forget-password/', include('apps.account.forgetPassword.urls')),
    # static data url
    path('agencies/', include('apps.agency.urls')),
    path('products/', include('apps.products.urls')),
    path('vendors/', include('apps.vendors.urls')),
    path('customers/', include('apps.customers.urls')),
    # orders app url
    path('orders/', include('apps.orders.urls')),
    path('purchase/', include('apps.purchase.urls')),
    path('bank-entries/', include('apps.bankentries.urls')),
    path('quicknotes/', include('apps.quicknotes.urls')),
    path('quotations/', include('apps.quotations.urls')),
    path('vouchers/', include('apps.voucher.urls')),
    path('invoices/', include('apps.invoice.urls')),
    path('expences/', include('apps.expences.urls')),
    path('net-payment/', include('apps.netpayment.urls')),
    path('loan/', include('apps.loan.urls')),
    path('sales/', include('apps.sales.urls')),
    path('api/', include('rest.urls')),
    path('post-api/', include('rest.post_urls'))
]
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/customers/urls.py
from django.urls import path
from apps.customers import views

urlpatterns = [
    path('', views.Customers, name="customer"),
    path('add-customer', views.Add_Customer, name="add-customer"),
    path('update-customer/<pk>', views.Update_Customer, name="update-customer")
]

rest/urls.py
from django.urls import path, include
from rest import views
from rest_framework import routers

 
router = routers.DefaultRouter()
# router.register(r'users', views.UserViewSet)
# router.register(r'groups', views.GroupViewSet)
router.register(r'agency', views.AgencyViewSet)
router.register(r'notifications', views.NotificationViewSet)
router.register(r'attendances', views.AttendanceViewSet)
router.register(r'vendors', views.VendorsViewSet)
router.register(r'products', views.ProductsViewSet)
router.register(r'customers', views.CustomersViewSet)
router.register(r'customer-delivery-address', views.CustomerDeliverAddressViewSet)
router.register(r'po-material-info', views.POMaterialInfoViewSet)
router.register(r'po-number', views.POViewSet)
router.register(r'material-info', views.MaterialInfoWithInfoViewSet)
router.register(r'orders', views.OrderViewSet)
router.register(r'po-number', views.POViewSet)
router.register(r'quicknotes', views.QuickNotesViewSet)


urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

apps/customers/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone

# Create your models here.

CATEGORY_CHOICES =(
    ("0", "Personal"),
    ("1", "Registered Account"),
)


""" Customer bank account models"""
class CustomerBankAccounts(models.Model):
    Customer_Name = models.CharField(max_length=100, null=True, blank=True)
    Category = models.CharField(max_length=1, choices=CATEGORY_CHOICES, null=True, blank=True)
    Account_No = models.CharField(max_length=100, null=True, blank=True)
    IFSC_Code = models.CharField(max_length=100, null=True, blank=True)
    Branch = models.CharField(max_length=100, null=True, blank=True)
    Register_Phone = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return '{0} - {1}'.format(self.Customer_Name, self.Branch)


""" Customer GST Billing Address """
class CustomerGSTBillingAddress(models.Model):
    GST_No = models.CharField(max_length=100, null=True, blank=True)
    Scan_Copy = models.FileField(upload_to ='uploads/%Y/%m/%d/', blank=True, null=True)
    Address = models.CharField(max_length=100, null=True, blank=True)
    City = models.CharField(max_length=20, null=True, blank=True)
    State = models.CharField(max_length=30, null=True, blank=True)
    Zip = models.CharField(max_length=10, null=True, blank=True)
    Country = models.CharField(max_length=30, null=True, blank=True)
    Location_Url = models.URLField(max_length=100, null=True, blank=True)
    Mobile = models.CharField(max_length=20, null=True, blank=True)
    Mail_Id = models.CharField(max_length=50, null=True, blank=True)
    Photo = models.FileField(upload_to ='uploads/%Y/%m/%d/', blank=True, null=True)

    def __str__(self):
        return '{0} - {1}'.format(self.GST_No, self.City)


""" Delivery Address Models """
class CustomerDeliveryAddress(models.Model):
    Customer_Name = models.CharField(max_length=200, null=True, blank=True)
    Branch = models.CharField(max_length=200, null=True, blank=True)
    URL_Location_Of_The_Unloading_Place = models.URLField(max_length=200, null=True, blank=True)
    URL_Office_Location  = models.URLField(max_length=200, null=True, blank=True)
    URL_Of_Owner_House  = models.URLField(max_length=200, null=True, blank=True)
    Invoice_Submitting_URL = models.URLField(max_length=200, null=True, blank=True)
    Payment_Collecting_URL = models.URLField(max_length=200, null=True, blank=True)
    Add_other_URL = models.URLField(max_length=200, null=True, blank=True)

    def __str__(self):
        return '{0} - {1}'.format(self.Customer_Name, self.Branch)


POSITION_CHOICES = (
    ("PH", "Purchase Head"),
    ("AH", "Account Head"),
    ("QH", "QC Head"),
    ("PU", "Payment Head"),
    ("US", "Unloading Suprivisor"),
    ("SP", "Security"),
)

GST_TYPE = (
    ("0", "GST Registered"),
    ("1", "Unregistered")
)
 
""" Customer Address """
class CustomerStaff(models.Model):
    Name = models.CharField(max_length=100, null=True, blank=True) 
    Contact_No = models.CharField(max_length=20, null=True, blank=True)
    Email = models.EmailField(max_length=30, null=True, blank=True)
    Position = models.CharField(max_length=2, choices=POSITION_CHOICES) 
    Location = models.CharField(max_length=100, null=True, blank=True) 
    City = models.CharField(max_length=50, null=True, blank=True)
    Zip = models.CharField(max_length=50, null=True, blank=True)
    State = models.CharField(max_length=50, null=True, blank=True) 
    Country = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return '{0} - {1}'.format(self.Name, self.Position)


"""delivery address for sales company should be only one"""
class Customer(models.Model):
    # map customer name
    User = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    Founder_Name = models.CharField(max_length=100, null=True, blank=True)
    Company_Name = models.CharField(max_length=100, null=True, blank=True)
    Founder_Phone = models.CharField(max_length=50, null=True, blank=True)
    Founder_Email = models.CharField(max_length=50, null=True, blank=True)
    Founder_Address = models.TextField(null=True, blank=True)
    Customer_Staff_Account = models.ManyToManyField(CustomerStaff)
    Bank_Account = models.ManyToManyField(CustomerBankAccounts)
    Delivery_Address = models.ManyToManyField(CustomerDeliveryAddress)
    GST_Type = models.CharField(max_length=1, choices=GST_TYPE)
    GST_No = models.ForeignKey(CustomerGSTBillingAddress, on_delete=models.CASCADE, null=True, blank=True)
    PAN_No = models.CharField(max_length=100, null=True, blank=True)
    PAN_Scan_Copy = models.FileField(upload_to ='uploads/%Y/%m/%d/', blank=True, null=True)
    No_Of_Project = models.CharField(max_length=10, null=True, blank=True)
    Remarks = models.TextField(null=True, blank=True)
    Payment_Terms = models.CharField(max_length=100, null=True, blank=True)
    published = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.Founder_Name




















"""
po number

fields -> (po applicable or not applicable), 
if applicable 
    ponumber
    poquantity
    porate
    podate
else
    salesrate
    order recieved date
"""

"""
bankaccount
=================
account no, ifsc code, branch, register phone

"""

"""
agencies

old
==========
name, email, phone, logo, 
new
============
gstno , pan no, certification, tin (optional), bankaccount(as foreign), phone number, mailid

"""


"""
customer detail add 
=========================
agency
user
customer name
material name, offer price, quantity,noofloadsload, expected date, quality,  
for every materiaal need to add moisiture
"""

"""
moisture
if appicable (%)
else
dont put %
"""


""" remarks (notes)"""









"""
material
=============

product - select
price





"""

apps/customers/views.py
from django.shortcuts import render, redirect
from apps.customers.models import Customer
from apps.agency.models import Agency
from django.contrib import messages
from apps.customers import forms
# Create your views here.


def Customers(request):
    active = Agency.objects.all().filter(Active=True)
    context = {
        'agency_obj' : Agency.objects.all(),
        'active_agency_obj' : active,
        'customer_obj' : Customer.objects.filter(),
    }
    return render(request, 'customers/customer.html', {'obj':context})


def Add_Customer(request):

    cf = forms.CustomerForm(request.POST, request.FILES or None)
    csf = forms.CustomerStaffForm(request.POST or None)
    cdaf = forms.CustomerDeliveryAddressForm(request.POST or None)
    cbaf = forms.CustomerGSTBillingAddressForm(request.POST, request.FILES or None)
    cacf = forms.CustomerBankAccountsForm(request.POST or None)
    
    active = Agency.objects.all().filter(Active=True)
    context = {
        'agency_obj' : Agency.objects.all(),
        'active_agency_obj' : active,
        'customer_form': cf,
        'customer_staff_form': csf,
        'customer_delivery_address_form': cdaf,
        'customer_billing_address_form': cbaf,
        'customer_bank_accounts_form': cacf,
    }

    if request.method == 'POST':
        getColumn = list(request.POST.keys())


        if getColumn[2] == 'Category':
            if request.POST['Category'] != '':
                obj = cacf.save()
                messages.success(request, 'Customer Bank Account Added. !!!')
                return redirect('/customers/add-customer')
            else:
                messages.error(request, 'Address not found. !!!') 

        elif getColumn[1] == 'GST_No':
            if request.POST['GST_No'] != '':
                obj = cbaf.save()
                messages.success(request, 'Customer GST No Added. !!!')
                return redirect('/customers/add-customer')
            else:
                messages.error(request, 'Customer GST No not found. !!!') 

        elif getColumn[2] == 'Branch':
            if request.POST['Branch'] != '':
                obj = cdaf.save()
                messages.success(request, 'Customer Delivery Address Added. !!!')
                return redirect('/customers/add-customer')
            else:
                messages.error(request, 'Customer delivery address not found. !!!') 

        
        elif getColumn[1] == 'Name':
            if request.POST['Name'] != '':
                obj = csf.save()
                messages.success(request, 'Customer Staff Detail Added. !!!')
                return redirect('/customers/add-customer')
            else:
                messages.error(request, 'Customer staff detail not found. !!!')     
 
        elif getColumn[1] == 'Founder_Name':

            if request.POST['Founder_Name'] != '':
                obj = cf.save()
                messages.success(request, 'Customer Detail Added. !!!')
                return redirect('/customers/add-customer')
            else:
                messages.error(request, 'Founder Name detail not found. !!!') 

                

    return render(request, 'customers/customer-add.html', {'obj':context})


def Update_Customer(request, pk=None):
    customer_data = Customer.objects.get(id=pk)
    cm = forms.CustomerForm(request.POST or request.FILES or None, instance=customer_data)
    active = Agency.objects.all().filter(Active=True)
    context = {
        'cm' : cm,
        'agency_obj' : Agency.objects.all(),
        'active_agency_obj' : active,
    }

    if request.method == 'POST':

        if request.POST['Founder_Name'] != '':
            obj = cm.save()
            messages.success(request, 'Customer Updated. !!!')
        else:
            messages.error(request, 'Customer Name is empty !!!')

    return render(request, 'customers/customer-update.html', {'obj':context})

templates/customers/customer-add.html
{% extends "_base.html" %}
{% load crispy_forms_tags %}


{% block content %}

<a href="{% url 'customer' %}" class="btn m-2 btn-sm"><i class="fa fa-chevron-left" aria-hidden="true"></i> Back</a>

{% if messages %}
    {% for message in messages %}
    <div {% if message.tags %} class="alerts mx-3 alert-{{ message.tags }}" {% endif %}> {{ message }} </div>
    {% endfor %}
{% endif %}


<div class="card p-3 mb-3 mx-3 box-2">
    <h6 class="fw-bold">Add Customer</h6>
    <hr class="my-2">
    {% crispy obj.customer_form %}
</div>

<div class="card p-3 mb-3 mx-3 box-2">
    <h6 class="fw-bold">Add Customer Staff Info</h6>
    <hr class="my-2">
    {% crispy obj.customer_staff_form %}
</div>

<div class="card p-3 mb-3 mx-3 box-2">
    <h6 class="fw-bold">Add Customer Delivery Address</h6>
    <hr class="my-2">
    {% crispy obj.customer_delivery_address_form %}
</div>
        
<div class="row mx-0 mb-3">
    <div class="col-6 pe-1">
        <div class="card p-3 mb-3 mx-1 box-2">
            <h6 class="fw-bold">Add GST No</h6>
            <hr class="my-2">
            {% crispy obj.customer_billing_address_form %}
        </div>
    </div>
    <div class="col-6 ps-1">
        <div class="card p-3 mb-3 mx-1 box-2">
            <h6 class="fw-bold">Add Customer Bank Accounts</h6>
            <hr class="my-2">
            {% crispy obj.customer_bank_accounts_form %}
        </div>
    </div>
</div>


{% endblock %}

{% block script %}

    <style>
        #div_id_PAN_Scan_Copy .custom-file-label, #div_id_Scan_Copy .custom-file-label, #div_id_Photo .custom-file-label{
            display:none !important;
        }
        #div_id_PAN_Scan_Copy .custom-file, #div_id_Scan_Copy .custom-file, #div_id_Photo .custom-file{
            padding: 0 !important;
        }
        .alerts{
        padding: 5px 15px;
        margin-bottom: 10px;
        color: white;
        font-weight: bold;
        border-radius: 5px;
    }
    .alert-error{
        background: #dc3545;
    }
    .alert-success{
        background:#0f5132 !important; 
    }
    </style>

    <script>
        $(document).ready(function(){

            $('.vendorMenu').addClass('active')

            var url = 'http://127.0.0.1:8000/api/'
            var csrftoken = $('meta[name="csrf-token"]').attr('content')
            var userid = $('#user-id').attr('data-id')
            var agencyid = $('#user-id').attr('data-id')
            $('#id_User').val(userid)
            $.ajaxSetup({
                headers: { 'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content') }
            });

            $('#example').DataTable()

            $('#id_Company_Name, #id_Vendor_Company_Name').change(function(){
                var vn = $('#id_Company_Name').val()
                $('#id_Company_Name, #id_Vendor_Company_Name').val(vn)
            })











            // delete method
            var deleteProduct = document.getElementById('deleteMethod')
                deleteProduct.addEventListener('show.bs.modal', function (event) {
                // Button that triggered the modal
                var button = event.relatedTarget
                // Extract info from data-bs-* attributes
                var id = button.getAttribute('data-bs-whatever')
                // If necessary, you could initiate an AJAX request here
                $('#deleteMethod .dlt').attr('data-id', id)
                DELETEMethod()
            })

            function DELETEMethod() {
                $('#deleteMethod .dlt').click(function () {
                    var customurl = $(this).attr('data-url')
                    var key = $(this).attr('data-col')
                    var value = $(this).attr('data-id')
                    var baseurl = url + customurl + '/' + value
                    var params = { [key]: value };
                    $.ajax({
                        type: "DELETE",
                        url: baseurl,
                        contentType: "application/json",
                        dataType: "json",
                        data: JSON.stringify(params),
                        headers: {
                            'X-CSRFToken': csrftoken
                        },
                    });
                    $('.row_' + value).remove()
                    $('#deleteMethod').modal('toggle');
                })
            }
        })
    </script>
{% endblock %})

templates/customers/customer-update.html
{% extends "_base.html" %}
{% load crispy_forms_tags %}    

{% block content %}

<a href="{% url 'customer' %}" class="btn btn-sm m-2"><i class="fa fa-chevron-left" aria-hidden="true"></i> Back</a>

{% if messages %}
    {% for message in messages %}
    <div {% if message.tags %} class="alerts mx-3 alert-{{ message.tags }}" {% endif %}> {{ message }} </div>
    {% endfor %}
{% endif %}


<div class="card p-3 mb-3 mx-3 box-2">
    <h6 class="fw-bold">Update Customer</h6>
    <hr class="my-2">
    {% crispy obj.cm %}
</div>




{% endblock %}

{% block script %}

    <style>
        #div_id_PAN_Scan_Copy .custom-file-label, #div_id_Scan_Copy .custom-file-label, #div_id_Photo .custom-file-label{
            display:none !important;
        }
        #div_id_PAN_Scan_Copy .custom-file, #div_id_Scan_Copy .custom-file, #div_id_Photo .custom-file{
            padding: 0 !important;
        }
        .alerts{
        padding: 5px 15px;
        margin-bottom: 10px;
        color: white;
        font-weight: bold;
        border-radius: 5px;
    }
    .alert-error{
        background: #dc3545;
    }
    .alert-success{
        background:#0f5132 !important; 
    }
    </style>

    <script>
        $(document).ready(function(){

            $('.vendorMenu').addClass('active')

        })
    </script>
{% endblock %})